In [1]:
import torch
import numpy as np
import torch.nn as nn

In [2]:
a = torch.tensor([[[1,0,0],[4,5,0]], [[1,0,0],[4,5,0]]],dtype=torch.float32)

In [3]:
print(a)

tensor([[[1., 0., 0.],
         [4., 5., 0.]],

        [[1., 0., 0.],
         [4., 5., 0.]]])


In [6]:
def construct_mask(tensor_in, padding_index = 0):
    mask = tensor_in == padding_index
    float_mask = mask.type(dtype=torch.float32)
    float_mask =  float_mask.masked_fill(mask=mask, value=-1e-20)
    return float_mask

In [7]:
mask = construct_mask(a, padding_index = 0)
mask

tensor([[[ 0.0000, -0.0000, -0.0000],
         [ 0.0000,  0.0000, -0.0000]],

        [[ 0.0000, -0.0000, -0.0000],
         [ 0.0000,  0.0000, -0.0000]]])

In [8]:
a + mask

tensor([[[ 1.0000, -0.0000, -0.0000],
         [ 4.0000,  5.0000, -0.0000]],

        [[ 1.0000, -0.0000, -0.0000],
         [ 4.0000,  5.0000, -0.0000]]])

In [31]:
lengths = [0,1,2,3,4,5,6,7]
max_seq_len = 7
batch_size = len(lengths)

In [32]:
m = torch.zeros(max_seq_len,dtype=torch.float32)

In [33]:
m

tensor([0., 0., 0., 0., 0., 0., 0.])

In [36]:
mask = torch.zeros(batch_size,max_seq_len)
for i in range(batch_size):
    for j in range(lengths[i],max_seq_len):
        mask[i,j] = -1

In [37]:
mask

tensor([[-1., -1., -1., -1., -1., -1., -1.],
        [ 0., -1., -1., -1., -1., -1., -1.],
        [ 0.,  0., -1., -1., -1., -1., -1.],
        [ 0.,  0.,  0., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])