In [1]:
import torch
import numpy as np
import torch.nn as nn
from collections import deque

In [2]:
a = torch.tensor([[1,2,3],[4,5,6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [3]:
b = torch.tensor([[1,2,3],[4,5,6]])
b

tensor([[1, 2, 3],
        [4, 5, 6]])

In [4]:
torch.cat([a,b],dim=1)

tensor([[1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6]])

In [6]:
a+b

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])