In [1]:
import torch
import numpy as np
import torch.nn as nn

In [2]:
a = torch.tensor([1,2,3])
print(a.dtype)

torch.int64


In [3]:
b = torch.tensor([[1,2,3],[7,8,9]])
c = torch.tensor([[4,5,6],[10,11,12.01]])
print(b.shape)
print(c.shape)

torch.Size([2, 3])
torch.Size([2, 3])


In [4]:
a

tensor([1, 2, 3])

In [5]:
b

tensor([[1, 2, 3],
        [7, 8, 9]])

In [6]:
c.tanh()

tensor([[0.9993, 0.9999, 1.0000],
        [1.0000, 1.0000, 1.0000]])

In [47]:
torch.FloatTensor(4)

tensor([-302414213229597033651907632608313344.0000,
                                            0.0000,
                                            0.0000,
                                            0.0000])

In [46]:
torch.randn(4)

tensor([ 0.7006,  0.4387,  0.1736, -0.3103])