In [1]:
import torch
import numpy as np
import torch.nn as nn

In [2]:
a = torch.tensor([1,2,3])
print(a.dtype)

torch.int64


In [7]:
b = torch.tensor([[1,2,3],[7,8,9]])
c = torch.tensor([[4,5,6],[10,11,12.01]])
print(b.shape)
print(c.shape)

torch.Size([2, 3])
torch.Size([2, 3])


In [8]:
a

tensor([1, 2, 3])

In [9]:
b

tensor([[1, 2, 3],
        [7, 8, 9]])

In [10]:
c.tanh()

tensor([[0.9993, 0.9999, 1.0000],
        [1.0000, 1.0000, 1.0000]])