In [2]:
import torch
import numpy as np
import torch.nn as nn

In [64]:
a = torch.tensor([[[1,0,0],[4,5,0]], [[1,0,0],[4,5,0]]],dtype=torch.float32)

In [65]:
print(a)

tensor([[[1., 0., 0.],
         [4., 5., 0.]],

        [[1., 0., 0.],
         [4., 5., 0.]]])


In [66]:
b = a != 0

In [67]:
print(b)

tensor([[[1, 0, 0],
         [1, 1, 0]],

        [[1, 0, 0],
         [1, 1, 0]]], dtype=torch.uint8)


In [68]:
b = b.type(dtype=torch.float32)

In [69]:
print(b)

tensor([[[1., 0., 0.],
         [1., 1., 0.]],

        [[1., 0., 0.],
         [1., 1., 0.]]])


In [70]:
a * b

tensor([[[1., 0., 0.],
         [4., 5., 0.]],

        [[1., 0., 0.],
         [4., 5., 0.]]])

In [109]:
def construct_mask(self, tensor_in, padding_index = 0):
    mask = tensor_in == padding_index
    float_mask = mask.type(dtype=torch.float32)
    float_mask =  float_mask.masked_fill(mask=mask, value=-1e-20)
    return float_mask

In [110]:
mask = construct_mask(a, padding_index = 0)
mask

tensor([[[ 0.0000, -0.0000, -0.0000],
         [ 0.0000,  0.0000, -0.0000]],

        [[ 0.0000, -0.0000, -0.0000],
         [ 0.0000,  0.0000, -0.0000]]])

In [111]:
a + mask

tensor([[[ 1.0000, -0.0000, -0.0000],
         [ 4.0000,  5.0000, -0.0000]],

        [[ 1.0000, -0.0000, -0.0000],
         [ 4.0000,  5.0000, -0.0000]]])